version: "3.9"
services:
  lingventa_service:
    build:
      dockerfile: Dockerfile
    container_name: lingventa_service
    ports:
      - "8080:8080"
    environment:
      - PROFILE=docker
    depends_on:
      - clinic_db
  open_meteo_db:
    image: 'postgres'
    container_name: open_meteo_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=welcome1
      - POSTGRES_DB=open_meteo_db
