openapi: 3.0.0
info:
  title: Lingventa API
  version: 0.0.1
paths:
  /statistics:
    get:
      operationId: getHistoricalMeteo
      summary: Return sunrise, sun set and avg
      parameters:
        - in: query
          name: latitude
          required: true
          schema:
            type: string
            pattern: '[0-9]*\.[0-9]*'
        - in: query
          name: longitude
          required: true
          schema:
            type: string
            pattern: '[0-9]*\.[0-9]*'
      responses:
        200:
          description: 'Meteo Statistic'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeteoStatistic'
        400:
          description: Bad request. Latitude and longitude are required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

components:
  schemas:
    MeteoStatistic:
      type: object
      properties:
        dates:
          type: array
          items:
            type: string
        sunrise:
          type: array
          items:
            type: string
        sunset:
          type: array
          items:
            type: string
        precipitation_sum:
          type: array
          items:
            type: number
            format: float
    ApiError:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
